// Module 5 — protobuf-generated message types.
// Generated from proto/messages.proto by prost-build at compile time.
// Do not edit this file — change the .proto and rebuild.

// prost-generated code triggers some lints we can't control.
#![allow(clippy::all, clippy::pedantic)]

include!(concat!(env!("OUT_DIR"), "/pb_ipc.rs"));
