[package]
name    = "pb-identity"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
pb-ipc    = { workspace = true }
pb-config = { workspace = true }
tokio     = { workspace = true }
uuid      = { workspace = true }
thiserror = { workspace = true }
tracing   = { workspace = true }
