//! Blocklist match benchmark, Module 21.
//!
//! Enforces the README perf-contract budget for Module 21:
//!
//! > Module 21 blocklist match: < 100 µs P99 on an 80k-entry tree.
//!
//! The bench builds a synthetic 80k-entry [`RadixTree`] of host rules
//! and measures three call shapes:
//!
//!   * **hit (deep label)** — `ads-12345.example` matches a leaf rule
//!     near the deep end of the tree (5 labels). The label-walk worst
//!     case among realistic shapes.
//!   * **miss** — `unrelated-host.example` walks until no descendant
//!     edge matches, then returns `None`. Walks the full label list of
//!     the candidate.
//!   * **near-root** — `tracker.com` matches a top-level wildcard rule
//!     after one label. Cheapest realistic match shape.
//!
//! Synthetic vs real EasyList: this bench generates names from a small
//! fixed-size alphabet so the tree shape is deterministic across runs.
//! The matcher complexity is dominated by label count + radix-tree
//! depth, both of which the synthetic tree reproduces faithfully.
//! Switching to a real EasyList snapshot would only change constant
//! factors, not the budget verdict.

use criterion::{black_box, criterion_group, criterion_main, Criterion};
use pb_network::{BlockKind, RadixTree, Rule};

/// Build a deterministic 80k-entry rule set spread across a wide,
/// shallow tree (mirrors EasyList shape — many TLD+1 names, a long
/// tail of subdomains).
fn synthetic_rules(count: usize) -> Vec<Rule> {
    let mut rules = Vec::with_capacity(count);
    let kinds = [
        BlockKind::Ad,
        BlockKind::Tracker,
        BlockKind::FingerprintAttempt,
    ];
    let mut i = 0usize;
    // 1k top-level wildcards: tracker0.com, tracker1.com, ...
    while i < count.min(1000) {
        rules.push(Rule::host(format!("tracker{i}.com"), kinds[i % 3]));
        i += 1;
    }
    // Remainder spread across deep subdomains so the radix tree
    // exercises label-walk depth, not just breadth.
    let mut j = 0usize;
    while i < count {
        let host = format!("ads-{j}.subnet-{}.tracker{}.com", j % 64, j % 1000);
        rules.push(Rule::host(host, kinds[i % 3]));
        i += 1;
        j += 1;
    }
    rules
}

fn bench_blocklist_match(c: &mut Criterion) {
    const TREE_SIZE: usize = 80_000;
    let rules = synthetic_rules(TREE_SIZE);
    let tree = RadixTree::from_rules(&rules);

    c.bench_function("blocklist_match_hit_deep", |b| {
        // Matches a deep-subdomain rule generated by the loop above
        // (j = 12345 -> "ads-12345.subnet-9.tracker345.com").
        b.iter(|| tree.match_host(black_box("ads-12345.subnet-9.tracker345.com")));
    });

    c.bench_function("blocklist_match_hit_near_root", |b| {
        // Matches one of the 1k top-level wildcards after one label.
        b.iter(|| tree.match_host(black_box("sub.tracker500.com")));
    });

    c.bench_function("blocklist_match_miss", |b| {
        // No descendant edge matches at any depth — returns None
        // after walking the candidate's full label list.
        b.iter(|| tree.match_host(black_box("never-blocked-host.example")));
    });

    c.bench_function("blocklist_match_miss_long_subdomain", |b| {
        // Worst-case miss: 6-label hostname none of whose suffix
        // walks find an edge. Pins the upper bound on label-walk
        // cost.
        b.iter(|| tree.match_host(black_box("a.very.long.unrelated.fake-host.example.test")));
    });
}

criterion_group!(benches, bench_blocklist_match);
criterion_main!(benches);
