[package]
name    = "pb-fingerprint"
version.workspace = true
edition.workspace = true

# NOTE: pb-fingerprint will use unsafe FFI for Gecko WebIDL overrides.
# unsafe is intentionally NOT forbidden in this crate.

[dependencies]
pb-ipc    = { workspace = true }
pb-config = { workspace = true }
uuid      = { workspace = true }
thiserror = { workspace = true }
tracing   = { workspace = true }
